name: API Key Request
description: Request an API key
title: "[req]: "
body:
  - type: input
    attributes:
      label: Product
      description: "The product you need an API key for (eg. Flare DA Layer)."
    validations:
      required: true

  - type: input
    attributes:
      label: Network
      description: "The network you need an API key for (eg. Flare Mainnet or Songbird Canary-Network)."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Purpose
      description: "A brief explanation of what you intend to use this API key for."
    validations:
      required: true

  - type: input
    attributes:
      label: Your Discord or Telegram handle
    validations:
      required: true

  - type: input
    attributes:
      label: Your Email
    validations:
      required: true
